#!/bin/sh
###############################################################################
# Copyright (c) 2006 Silicon Graphics, Inc. All Rights Reserved.
# Copyright (c) 2006-2010 Krell Institute All Rights Reserved.
#
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 2 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc., 59 Temple
# Place, Suite 330, Boston, MA  02111-1307  USA
################################################################################
rm -f regression_results
HOMEDIR=$(pwd)
touch regression_results
cd $HOMEDIR/src/regression/views
rm -f testresults*
./runall
cat testresults_* > $HOMEDIR/regression_results
cd $HOMEDIR/src/regression/usertime/usertime1
rm -f testresults*
./runall
cat testresults_* >> $HOMEDIR/regression_results
cd $HOMEDIR/src/regression/hwc/hwc1
rm -f testresults*
./runall
cat testresults_* >> $HOMEDIR/regression_results
