#! /bin/sh
################################################################################
# Copyright (c) 2004 Silicon Graphics, Inc. All Rights Reserved.
#
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 2 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc., 59 Temple
# Place, Suite 330, Boston, MA  02111-1307  USA
################################################################################

if test -r "Makefile"; then
    make distclean
fi

rm -rf autom4te.cache libltdl
rm -f aclocal.m4 compile config.guess config.h.in config.sub
rm -f configure depcomp install-sh ltmain.sh missing mkinstalldirs

rm -f Makefile.in
rm -f collectors/Makefile.in
rm -f collectors/pcsamp/Makefile.in
rm -f examples/Makefile.in
rm -f examples/libssf/Makefile.in
rm -f examples/libssf/tool/Makefile.in
rm -f libssf/Makefile.in

if test "$1" = "--clean"; then
    exit
fi

aclocal
libtoolize --ltdl --copy
autoheader
automake --foreign --add-missing --copy
autoconf
