#! /bin/sh
################################################################################
# Copyright (c) 2005 Silicon Graphics, Inc. All Rights Reserved.
#
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 2 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc., 59 Temple
# Place, Suite 330, Boston, MA  02111-1307  USA
################################################################################

echo "running bootstrap on top level source directory"
aclocal
libtoolize --force --ltdl --copy
mv -f ../../ltmain.sh .
mv -f ../../config.guess .
mv -f ../../config.sub .
autoheader
automake --foreign --add-missing --copy 
autoconf
#
# configure test executables to allow for alternative compilers
#
echo "running bootstrap on test/executables"
cd test/executables
aclocal
automake --foreign --add-missing --copy
autoconf
cd ../..
#
# configure test mpi executables to allow for alternative compilers
#
echo "running bootstrap on test/executables/mpi"
cd test/executables/mpi
aclocal
automake --foreign --add-missing --copy
autoconf
cd ../../..
#
# configure dyninst tests for alternative installs of dyninst
#
echo "running bootstrap on test/src/dyninst"
cd test/src/dyninst
aclocal
libtoolize --force --ltdl --copy
automake --foreign --add-missing --copy
autoconf
cd ../../..

echo "finished - running bootstrap on all directories"

