#!/bin/sh
################################################################################
# Copyright (c) 2005 Silicon Graphics, Inc. All Rights Reserved.
#
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 2 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc., 59 Temple
# Place, Suite 330, Boston, MA  02111-1307  USA
################################################################################

if [ "$OPENSS_INSTALL_DIR" = "" ]
then
  echo "OPENSS_INSTALL_DIR not set."
  echo "For oss developers that's usually .../GUI/plugin/lib/openspeedshop"
  echo "- or -"
  echo "export OPENSS_INSTALL_DIR=$OPENSS_PLUGIN_PATH/../.."
  if [ "$OPENSS_PLUGIN_PATH" != "" ]
  then
    export OPENSS_INSTALL_DIR=$OPENSS_PLUGIN_PATH/../..;
    echo "WARNING: Defaulting to developers location..."
  fi 
#  exit
fi
if test -d plugins/panels
then
bootstrap;configure --prefix=$OPENSS_INSTALL_DIR --with-libunwind=/home/jeg/x86_64/root/usr --with-papi=/home/jeg/x86_64/papi_root --with-dpcl=/home/jeg/x86_64/root/usr --with-dyninst=/home/jeg/x86_64/root/usr --with-sqlite=/home/jeg/x86_64/root/usr --with-mpich2=/apps/x86_64/mpich2-1.0.2p1-gcc-3.4.3-tcpip --with-mpich=/home/jeg/x86_64/mvapich_root --with-mpich-driver=sandia ; make uninstall;make install;make dist; 
else
  echo NOTE: This must be run from the 'current' directory...
fi
