######################################################################
# Automatically generated by qmake (1.07a) Wed Apr 28 13:44:02 2004
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += qdir.h ../dirview/dirview.h
SOURCES += qdir.cpp ../dirview/dirview.cpp
