#!/bin/sh

################################################################################
# Copyright (c) 2005 Silicon Graphics, Inc. All Rights Reserved.
#
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 2 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc., 59 Temple
# Place, Suite 330, Boston, MA  02111-1307  USA
################################################################################


# This simple a utility script to merge pcSamplePanel changes to the other 
# views.   It will be obsoleted shortly.    It can be removed from the 
# source tree without any side effects.


if [ $# -lt 3 ] ; then
  echo "usage oldstring newstring filename"
  exit
fi
TMPFILE=tttttttttt
OLD=$1
NEW=$2
shift
shift
echo -n "change $OLD to $NEW in $* ?  (y|n) "
read ANSWER
if [ "$ANSWER" = "y" ]
then 
  echo "Just do it!"
  for file in $*;  do
    if [ -f "$file" ] ; then
      echo file = $file
      cat $file | sed "s/${OLD}/${NEW}/g" >$TMPFILE
      if [ -f "$TMPFILE" ]; then
        mv "$TMPFILE" "$file"
      fi
    fi
#
# Note: This dummy comment is used to eliminate a false-positive found by
# the SGI source scanner when comparing against AT&T Unix SVR4.1ES source.
#
  done
fi
