#!/bin/sh

################################################################################
# Copyright (c) 2005 Silicon Graphics, Inc. All Rights Reserved.
#
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 2 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc., 59 Temple
# Place, Suite 330, Boston, MA  02111-1307  USA
################################################################################


export SYSTYPE=`uname -s`
# echo SYSTYPE=$SYSTYPE
export SYSNAME=`uname -n`
# echo SYSNAME=$SYSNAME

if [[ $1 = --help ]]
then
  echo "openss [-cli] [executable] [experiment] [pid] [host] [--help]"
  echo "  where:"
  echo "    -cli:         brings up the future in command line mode"
  echo "    executable:   loads the executable file"
  echo "    experiment:   loads the exeriment file"
  echo "    pid:          attaches (or plans to attach) to process id"
  echo "    host:         targets processes on host machine, host"
  echo "    -fn fontname: sets the  font."
  echo "                  Doing an xlsfonts on Linux shows possible font"
  echo "                  candidates.   Otherwise -fn "fixed" should work."
  echo "    --help:       This help text."
  exit
fi

if [ "$OPENSPEEDSHOP_PLUGIN_PATH" = "" ]
then
  echo "OPENSPEEDSHOP_PLUGIN_PATH not set."
  echo "For oss developers that's usually .../GUI/plugin/lib/openspeedshop"
  exit
fi

export OPENSPEEDSHOP_GUI_RELOCATABLE_NAME=libopenss-GUI.so
export OPENSPEEDSHOP_GUI_ENTRY_POINT=gui_init
export OPENSPEEDSHOP_CLI_RELOCATABLE_NAME=posscli.so
export OPENSPEEDSHOP_CLI_ENTRY_POINT=cli_init
set +x
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$OPENSPEEDSHOP_PLUGIN_PATH
export LD_LIBRARYN32_PATH=$LD_LIBRARYN32_PATH:$LD_LIBRARY_PATH
# export OPENSPEEDSHOP_FONTNAME="-adobe-utopia-regular-r-normal--10-100-75-75-p-56-iso8859-1"
#if [[ $1 = -gui ]]
#then
#  $OPENSPEEDSHOP_PLUGIN_PATH/../../bin/openspeedshop -gui -fn $OPENSPEEDSHOP_FONTNAME $@
#else
#  $OPENSPEEDSHOP_PLUGIN_PATH/../../bin/openspeedshop $@
#fi
$OPENSPEEDSHOP_PLUGIN_PATH/../../bin/openspeedshop $@
