#! /bin/bash
#
#  This script is focused on running on LLNL systems
#
if [ "$1" == "help" -o "$1" = "--help" ]
then
  echo ""
  echo "Usage: This script automatically compiles smg2000 and sweep3d"
  echo "       using the Intel, PGI, and GNU compilers and the default MVAPICH MPI implementation."
  echo ""
  echo "       It then runs OpenSpeedShop on each of the smg2000 and sweep3d versions using:"
  echo "       the pcsamp, usertime, hwc, hwctime, io, iot, mpi, and mpit experiments."
  echo ""
  echo "       It verifies the results only by searching for a common expected value.  At this time"
  echo "       no performance ratios are tested for."
  echo ""
  exit
fi

#
#
debug_flag=1

. /usr/local/tools/dotkit/init.sh

##set -x
basedir=`pwd`

# Try looking for LLNL run environment
found_llnl=0

runcommand=`which srun`
if [ debug_flag == 1 ]
then
  echo "runcommand=" $runcommand
  echo "system type=" $SYS_TYPE
fi

if [ $SYS_TYPE ]; then
  echo " NOTE: SYS_TYPE=$SYS_TYPE"
fi

if [ $SYS_TYPE ]; then
  thissystype=$SYS_TYPE
  if [[ "$thissystype" == "chaos*" ]]; then
    echo "NOTE: chaos detected in SYS_TYPE defaulting to LLNL system type."
    found_llnl=1
    use openss_mrnet_x864_64
  else
    found_llnl=0
    echo "NOTE: chaos was not detected"
  fi
fi
# hard code for now.  Not why the above is failing
found_llnl=1

if [ $found_llnl == 0 ]
then
  echo "Did not find SYS_TYPE environment variable: Are we running this script on the correct system?"
  exit
fi

for testname in `ls *.tar.gz`
do
  if [ debug_flag == 1 ]
  then
     echo "1st loop, testname=" $testname
   fi
   NEWNAME=$(echo "$testname" | sed -e 's/.tar.gz//')
   if [ debug_flag == 1 ]
   then
     echo "1st loop, NEWNAME=" $NEWNAME
   fi
   cd $basedir
   if [ debug_flag == 1 ]
   then
     echo "1st loop, basedir=" $basedir
   fi

#thiscompiler="intel"
#  for thiscompiler in intel pgi gnu

#  loop here through a compiler list
   for thiscompiler in intel 
   do
     echo $thiscompiler  

if [ debug_flag == 1 ]
then
  echo "testsuffix=" $testsuffix
  echo "testCC=" $testCC
fi


hostabi=`uname -m`
ulimit -c unlimited
#
# setup the path and information with regards to building the MPI applicaton you will be running
#
testexe=$NEWNAME

currentdir=`pwd`
testpathbase=$currentdir

echo $currentdir

gunzip $testexe.tar.gz
tar -xvf $testexe.tar
gzip $testexe.tar
sysSED=`which sed`

if [ debug_flag == 1 ]
then
  echo "system sed command is" $sysSED
fi

cd $testexe

if [ "$testexe" == "smg2000" ]
then
  cd $currentdir/smg2000
  if [ "$thiscompiler" == "pgi" ]
  then
     $sysSED 's/mpicc/mpipgcc/' Makefile.include > newMakefile.include
  elif [ "$thiscompiler" == "intel" ]
  then
     $sysSED 's/mpicc/mpiicc-10.1.017/' Makefile.include > newMakefile.include
  fi
elif  [ "$testexe" == "sweep3d" ]
then
  cd $currentdir/sweep3d
  if [ "$thiscompiler" == "pgi" ]
  then
     $sysSED 's/mpif77/mpipgf77/' makefile > new_makefile
  elif [ "$thiscompiler" == "intel" ]
  then
     $sysSED 's/mpif77/mpiifort-10.1.017/' makefile > new_makefile
  fi
fi

thismpicc=`which mpicc`
if [ $found_llnl == 0 ]
then
  echo "which mpicc=" $thismpicc
fi

if [ "$testexe" == "smg2000" ]
then
  mv -f newMakefile.include Makefile.include
  make
elif  [ "$testexe" == "sweep3d" ]
then
  mv -f new_makefile makefile
  make mpi
fi

if [ "$testexe" == "smg2000" ]
then
   testpath=$testpathbase/smg2000/test
   testexepath=$testpath
   testexeargs='-n 35 35 35'
   testprogram=$testexepath/$testexe
elif [ "$testexe" == "sweep3d" ]
then
   testpath=$testpathbase/$testexe
   testexepath=$testpath
   testexeargs=''
   testprogram=$testexepath/$testexe.mpi
else
   testpath=$testpathbase/$testexe
   testexepath=$testpath
   testexeargs=''
   testprogram=$testexepath/$testexe
fi

#
# setup the OpenSpeedShop experiment type 
#
experiment=usertime
#experiment=pcsamp

sleep 2

#export OPENSS_DEBUG_OPENSS=1
#export OPENSS_DEBUG_MPIJOB=1
#export OPENSS_DEBUG_PROCESS=1
#export DYNINST_DEBUG_STARTUP=1
#export DYNINST_DEBUG_SYMTAB=1

cd $testpath

#
# setup the path to OpenSpeedShop
#
theopenss=`which openss`
#theopenss=/g/g24/jeg/chaos_4_x86_64_ib/opt/OSS-mrnet/bin/openss

echo "NOTE: Using openss=" $theopenss
echo "NOTE: Using the raw data directory storage environment variable: OPENSS_RAWDATA_DIR=" $OPENSS_RAWDATA_DIR

#
# Create the default test configuration file if it does not exist
#
if [ -a default_test_config ]
then
  echo "NOTE: Using default_test_config file which already exists"
else
  echo "NOTE: Creating default_test_config file"
cat > default_test_config << EOF
2
16
pgi
jegkas@gmail.com
EOF
fi

cat > common_commands << EOF
wait
expstatus
expview
EOF


if [ "$testexe" == "smg2000" ] 
then


cat > smg2000_intel_script.sh << EOF
#!/bin/bash
. /usr/local/tools/dotkit/init.sh
use openss_mrnet_x86_64
which openss
executable=`which smg2000`
echo "Current directory is:" `\$pwd`
echo "smg2000 executable path directory is:" \$executable
#
# Run all experiments
#

#
# Run pcsamp and analyze the results
#
openss -offline -f "/usr/bin/srun -N \$NodeCount -n \$RankCount -p pdebug ./smg2000 -n 25 25 25" pcsamp
ls *.openss | grep "smg2000-pcsamp\." > smg2000_intel_create_pcsamp
echo "-------------------------------------"
echo "BEGIN Analyzing smg2000 pcsamp experiment"
echo "-------------------------------------"
sed 's/^/exprestore -f /' smg2000_intel_create_pcsamp > new_input.script
echo "log -f smg2000_intel_pcsamp_results.log" >> new_input.script
cat common_commands >> new_input.script
openss -batch < new_input.script

grep "hypre_CyclicReduction (smg2000: cyclic_reduction.c,757)" smg2000_intel_pcsamp_results.log | cat > smg2000_intel_pcsamp_results.status

echo "-------------------------------------"
echo "END Analyzing smg2000 pcsamp experiment"
echo "-------------------------------------"

#
# Run usertime and analyze the results
#
openss -offline -f "/usr/bin/srun -N \$NodeCount -n \$RankCount -p pdebug ./smg2000 -n 25 25 25" usertime
ls *.openss | grep "smg2000-usertime\." > smg2000_intel_create_usertime

echo "-------------------------------------"
echo "BEGIN Analyzing smg2000 usertime experiment"
echo "-------------------------------------"
sed 's/^/exprestore -f /' smg2000_intel_create_usertime > new_input.script
echo "log -f smg2000_intel_usertime_results.log" >> new_input.script
cat common_commands >> new_input.script
openss -batch < new_input.script

grep "hypre_CyclicReduction (smg2000: cyclic_reduction.c,757)" smg2000_intel_usertime_results.log | cat > smg2000_intel_usertime_results.status

echo "-------------------------------------"
echo "END Analyzing smg2000 usertime experiment"
echo "-------------------------------------"
echo ""



openss -offline -f "/usr/bin/srun -N \$NodeCount -n \$RankCount -p pdebug ./smg2000 -n 25 25 25" hwc
ls *.openss | grep "smg2000-hwc\." > smg2000_intel_create_hwc

echo ""
echo "BEGIN Analyzing smg2000 hwc experiment"
sed 's/^/exprestore -f /' smg2000_intel_create_hwc > new_input.script
echo "log -f smg2000_intel_hwc_results.log" >> new_input.script
cat common_commands >> new_input.script
openss -batch < new_input.script

grep "hypre_CyclicReduction (smg2000: cyclic_reduction.c,757)" smg2000_intel_hwc_results.log | cat > smg2000_intel_hwc_results.status

echo "-------------------------------------"
echo "END Analyzing smg2000 hwc experiment"
echo "-------------------------------------"
echo ""


openss -offline -f "/usr/bin/srun -N \$NodeCount -n \$RankCount -p pdebug ./smg2000 -n 25 25 25" hwctime
ls *.openss | grep "smg2000-hwctime\." > smg2000_intel_create_hwctime

echo ""
echo "-------------------------------------"
echo "BEGIN Analyzing smg2000 hwctime experiment"
echo "-------------------------------------"
sed 's/^/exprestore -f /' smg2000_intel_create_hwctime > new_input.script
echo "log -f smg2000_intel_hwctime_results.log" >> new_input.script
cat common_commands >> new_input.script
openss -batch < new_input.script

grep "hypre_CyclicReduction (smg2000: cyclic_reduction.c,757)" smg2000_intel_hwctime_results.log | cat > smg2000_intel_hwctime_results.status

echo "-------------------------------------"
echo "END Analyzing smg2000 hwctime experiment"
echo "-------------------------------------"
echo ""


openss -offline -f "/usr/bin/srun -N \$NodeCount -n \$RankCount -p pdebug ./smg2000 -n 25 25 25" io
ls *.openss | grep "smg2000-io\." > smg2000_intel_create_io

echo ""
echo "-------------------------------------"
echo "BEGIN Analyzing smg2000 io experiment"
echo "-------------------------------------"
sed 's/^/exprestore -f /' smg2000_intel_create_io > new_input.script
echo "log -f smg2000_intel_io_results.log" >> new_input.script
cat common_commands >> new_input.script
openss -batch < new_input.script

grep "2016  __libc_open" smg2000_intel_io_results.log | cat > smg2000_intel_io_results.status

echo "-------------------------------------"
echo "END Analyzing smg2000 io experiment"
echo "-------------------------------------"
echo ""


openss -offline -f "/usr/bin/srun -N \$NodeCount -n \$RankCount -p pdebug ./smg2000 -n 25 25 25" iot
ls *.openss | grep "smg2000-iot\." > smg2000_intel_create_iot

echo ""
echo "-------------------------------------"
echo "BEGIN Analyzing smg2000 iot experiment"
echo "-------------------------------------"
sed 's/^/exprestore -f /' smg2000_intel_create_iot > new_input.script
echo "log -f smg2000_intel_iot_results.log" >> new_input.script
cat common_commands >> new_input.script
openss -batch < new_input.script

grep "2016  __libc_open" smg2000_intel_iot_results.log | cat > smg2000_intel_iot_results.status

echo "-------------------------------------"
echo "END Analyzing smg2000 iot experiment"
echo "-------------------------------------"
echo ""


openss -offline -f "/usr/bin/srun -N \$NodeCount -n \$RankCount -p pdebug ./smg2000 -n 5 5 5" mpi
ls *.openss | grep "smg2000-mpi\-" > smg2000_intel_create_mpi

echo ""
echo "-------------------------------------"
echo "BEGIN Analyzing smg2000 mpi experiment"
echo "-------------------------------------"
sed 's/^/exprestore -f /' smg2000_intel_create_mpi > new_input.script
echo "log -f smg2000_intel_mpi_results.log" >> new_input.script
cat common_commands >> new_input.script
openss -batch < new_input.script

grep "\$RankCount  PMPI_Finalize" smg2000_intel_mpi_results.log | cat > smg2000_intel_mpi_results.status

echo "-------------------------------------"
echo "END Analyzing smg2000 mpi experiment"
echo "-------------------------------------"
echo ""


openss -offline -f "/usr/bin/srun -N \$NodeCount -n \$RankCount -p pdebug ./smg2000 -n 5 5 5" mpit

#
# Find corresponding experiment database files and create files that can be used to restore the databases
#
ls *.openss | grep "smg2000-mpit\-" > smg2000_intel_create_mpit

#
# Use the corresponding experiment database file names to restore the database and print out the status and results for the experiments
#
echo ""
echo "-------------------------------------"
echo "BEGIN Analyzing smg2000 mpit experiment"
echo "-------------------------------------"
sed 's/^/exprestore -f /' smg2000_intel_create_mpit > new_input.script
echo "log -f smg2000_intel_mpit_results.log" >> new_input.script
cat common_commands >> new_input.script
openss -batch < new_input.script

grep "\$RankCount  PMPI_Finalize" smg2000_intel_mpi_results.log | cat > smg2000_intel_mpi_results.status

echo "-------------------------------------"
echo "END Analyzing smg2000 mpit experiment"
echo "-------------------------------------"
echo ""


#
# End of nested script
#
exit
EOF

echo "pwd=$pwd"

RUN_DIR=$testpath
echo "RUN_DIR=$RUN_DIR"
cd $RUN_DIR
REQ_WALLTIME=1:00
REQ_NNODES=2
REQ_SCRIPT="$RUN_DIR/smg2000_intel_script.sh"
#script smg2000_intel_script_results.txt
sh ${REQ_SCRIPT}

cat > smg2000_intel_email.sh << EOF
#! /bin/bash

# script to send test results email
# email subject
SUBJECT="LLNL OpenSpeedShop MPI smg2000 executable test results"
# Email To ?
EMAIL="jegkas@gmail.com"
# Email text/message
EMAILMESSAGE="/tmp/openss_test_message.txt"
echo " OpenSpeedShop Performance Tool SMG2000 Test Results" >\$EMAILMESSAGE
echo "" >>\$EMAILMESSAGE
echo " Intel compiler, $NodeCount Nodes \$RankCount ranks">> \$EMAILMESSAGE
thisuname=`uname -srnmo`
echo " System uname: " \$thisuname>> \$EMAILMESSAGE
thisdate=`date`
echo " Date/time of run: " \$thisdate>> \$EMAILMESSAGE
thisdir=`pwd`
echo " Directory where tests were run: " \$thisdir>> \$EMAILMESSAGE
echo "" >>\$EMAILMESSAGE
#
testval=`ls *.status | wc -l`
echo " Expected tests: 8">> \$EMAILMESSAGE
echo " Completed tests: " \$testval>> \$EMAILMESSAGE
#
# if the status file exists and has data then the test succeeded
# if the status file does not exist then the test did not complete and consider it failed
#
if [ -a smg2000_intel_pcsamp_results.status ]
then
  if [ -s smg2000_intel_pcsamp_results.status ]
  then
    echo " PCSAMP EXPERIMENT PASSED">> \$EMAILMESSAGE
  else
    echo " PCSAMP EXPERIMENT FAILED">> \$EMAILMESSAGE
  fi
else
  echo " PCSAMP EXPERIMENT FAILED">> \$EMAILMESSAGE
fi

#
# if the status file exists and has data then the test succeeded
# if the status file does not exist then the test did not complete and consider it failed
#
if [ -a smg2000_intel_usertime_results.status ]
then
  if [ -s smg2000_intel_usertime_results.status ]
  then
    echo " USERTIME EXPERIMENT PASSED">> \$EMAILMESSAGE
  else
    echo " USERTIME EXPERIMENT FAILED">> \$EMAILMESSAGE
  fi
else
  echo " USERTIME EXPERIMENT FAILED">> \$EMAILMESSAGE
fi

#
# if the status file exists and has data then the test succeeded
# if the status file does not exist then the test did not complete and consider it failed
#
if [ -a smg2000_intel_hwc_results.status ]
then
  if [ -s smg2000_intel_usertime_results.status ]
  then
    echo " HWC EXPERIMENT PASSED">> \$EMAILMESSAGE
  else
    echo " HWC EXPERIMENT FAILED">> \$EMAILMESSAGE
  fi
else
  echo " HWC EXPERIMENT FAILED">> \$EMAILMESSAGE
fi

#
# if the status file exists and has data then the test succeeded
# if the status file does not exist then the test did not complete and consider it failed
#
if [ -a smg2000_intel_hwctime_results.status ]
then
  if [ -s smg2000_intel_hwctime_results.status ]
  then
    echo " HWCTIME EXPERIMENT PASSED">> \$EMAILMESSAGE
  else
    echo " HWCTIME EXPERIMENT FAILED">> \$EMAILMESSAGE
  fi
else
  echo " HWCTIME EXPERIMENT FAILED">> \$EMAILMESSAGE
fi

#
# if the status file exists and has data then the test succeeded
# if the status file does not exist then the test did not complete and consider it failed
#
if [ -a smg2000_intel_io_results.status ]
then
  if [ -s smg2000_intel_io_results.status ]
  then
    echo " I/O EXPERIMENT PASSED">> \$EMAILMESSAGE
  else
    echo " I/O EXPERIMENT FAILED">> \$EMAILMESSAGE
  fi
else
  echo " I/O EXPERIMENT FAILED">> \$EMAILMESSAGE
fi

#
# if the status file exists and has data then the test succeeded
# if the status file does not exist then the test did not complete and consider it failed
#
if [ -a smg2000_intel_iot_results.status ]
then
  if [ -s smg2000_intel_iot_results.status ]
  then
    echo " I/O TRACE EXPERIMENT PASSED">> \$EMAILMESSAGE
  else
    echo " I/O TRACE EXPERIMENT FAILED">> \$EMAILMESSAGE
  fi
else
  echo " I/O TRACE EXPERIMENT FAILED">> \$EMAILMESSAGE
fi

#
# if the status file exists and has data then the test succeeded
# if the status file does not exist then the test did not complete and consider it failed
#
if [ -a smg2000_intel_mpi_results.status ]
then
  if [ -s smg2000_intel_mpi_results.status ]
  then
    echo " MPI EXPERIMENT PASSED">> \$EMAILMESSAGE
  else
    echo " MPI EXPERIMENT FAILED">> \$EMAILMESSAGE
  fi
else
  echo " MPI EXPERIMENT FAILED">> \$EMAILMESSAGE
fi

#
# if the status file exists and has data then the test succeeded
# if the status file does not exist then the test did not complete and consider it failed
#
if [ -a smg2000_intel_mpit_results.status ]
then
  if [ -s smg2000_intel_mpit_results.status ]
  then
    echo " MPI TRACE EXPERIMENT PASSED">> \$EMAILMESSAGE
  else
    echo " MPI TRACE EXPERIMENT FAILED">> \$EMAILMESSAGE
  fi
else
  echo " MPI TRACE EXPERIMENT FAILED">> \$EMAILMESSAGE
fi
#echo "This is an email message test">> \$EMAILMESSAGE
#echo "This is email text" >>\$EMAILMESSAGE
# send an email using /bin/mail
/bin/mail -s "\$SUBJECT" "\$EMAIL" < \$EMAILMESSAGE
EOF

# Send out the results for smg2000
EMAIL_REQ_SCRIPT="$RUN_DIR/smg2000_intel_email.sh"
sh ${EMAIL_REQ_SCRIPT}


elif [ "$testexe" == "sweep3d" ] 
then

cat > sweep3d_intel_script.sh << EOF
#!/bin/bash
. /usr/local/tools/dotkit/init.sh
use openss_mrnet_x86_64
which openss
executable=`which sweep3d.mpi`
echo "Current directory is:" `\$pwd`
echo "sweep3d.mpi executable path directory is:" \$executable
#
# Read in test parameters
#
# script defaults
NodeCount=2
RankCount=16
CompilerType="gnu"
EmailAddress="jegkas@gmail.com"

if [ -a default_test_config ] 
then
  echo "Current directory is:" `\$pwd`
else
  n=0
  while read curline; do
    n=`expr \$n + 1`
    echo "\$curline"
    echo "\$n" 

    if [ \$n == 1 ]
    then
       NodeCount=\$curline
    elif [ \$n == 2 ]
    then
       RankCount=\$curline
    elif [ \$n == 3 ]
    then
       CompilerType=\$curline
    elif [ \$n == 4 ]
    then
       EmailAddress=\$curline
    fi
  done < "default_test_config"
fi

#
if [ debug_flag == 1 ]
then
  echo "NodeCount: \$NodeCount"
  echo "RankCount: \$RankCount"
  echo "CompilerType: \$CompilerType"
  echo "EmailAddress: \$EmailAddress"
fi

#
# Run all experiments
#

#
# Run pcsamp and analyze the results
#
openss -offline -f "/usr/bin/srun -N \$NodeCount -n \$RankCount -p pdebug ./sweep3d.mpi" pcsamp
ls *.openss | grep "sweep3d.mpi-pcsamp\." > sweep3d_intel_create_pcsamp
echo "-------------------------------------"
echo "BEGIN Analyzing sweep3d.mpi pcsamp experiment"
echo "-------------------------------------"
sed 's/^/exprestore -f /' sweep3d_intel_create_pcsamp > new_input.script
echo "log -f sweep3d_intel_pcsamp_results.log" >> new_input.script
cat common_commands >> new_input.script
openss -batch < new_input.script

grep "source_ (sweep3d.mpi: source.f,2)." sweep3d_intel_pcsamp_results.log | cat > sweep3d_intel_pcsamp_results.status

echo "-------------------------------------"
echo "END Analyzing sweep3d.mpi pcsamp experiment"
echo "-------------------------------------"

#
# Run usertime and analyze the results
#
openss -offline -f "/usr/bin/srun -N \$NodeCount -n \$RankCount -p pdebug ./sweep3d.mpi" usertime
ls *.openss | grep "sweep3d.mpi-usertime\." > sweep3d_intel_create_usertime

echo "-------------------------------------"
echo "BEGIN Analyzing sweep3d.mpi usertime experiment"
echo "-------------------------------------"
sed 's/^/exprestore -f /' sweep3d_intel_create_usertime > new_input.script
echo "log -f sweep3d_intel_usertime_results.log" >> new_input.script
cat common_commands >> new_input.script
openss -batch < new_input.script

grep "source_ (sweep3d.mpi: source.f,2)." sweep3d_intel_usertime_results.log | cat > sweep3d_intel_usertime_results.status

echo "-------------------------------------"
echo "END Analyzing sweep3d.mpi usertime experiment"
echo "-------------------------------------"
echo ""



openss -offline -f "/usr/bin/srun -N \$NodeCount -n \$RankCount -p pdebug ./sweep3d.mpi" hwc
ls *.openss | grep "sweep3d.mpi-hwc\." > sweep3d_intel_create_hwc

echo ""
echo "BEGIN Analyzing sweep3d.mpi hwc experiment"
sed 's/^/exprestore -f /' sweep3d_intel_create_hwc > new_input.script
echo "log -f sweep3d_intel_hwc_results.log" >> new_input.script
cat common_commands >> new_input.script
openss -batch < new_input.script

grep "source_ (sweep3d.mpi: source.f,2)." sweep3d_intel_hwc_results.log | cat > sweep3d_intel_hwc_results.status

echo "-------------------------------------"
echo "END Analyzing sweep3d.mpi hwc experiment"
echo "-------------------------------------"
echo ""


openss -offline -f "/usr/bin/srun -N \$NodeCount -n \$RankCount -p pdebug ./sweep3d.mpi" hwctime
ls *.openss | grep "sweep3d.mpi-hwctime\." > sweep3d_intel_create_hwctime

echo ""
echo "-------------------------------------"
echo "BEGIN Analyzing sweep3d.mpi hwctime experiment"
echo "-------------------------------------"
sed 's/^/exprestore -f /' sweep3d_intel_create_hwctime > new_input.script
echo "log -f sweep3d_intel_hwctime_results.log" >> new_input.script
cat common_commands >> new_input.script
openss -batch < new_input.script

grep "source_ (sweep3d.mpi: source.f,2)." sweep3d_intel_hwctime_results.log | cat > sweep3d_intel_hwctime_results.status

echo "-------------------------------------"
echo "END Analyzing sweep3d.mpi hwctime experiment"
echo "-------------------------------------"
echo ""


openss -offline -f "/usr/bin/srun -N \$NodeCount -n \$RankCount -p pdebug ./sweep3d.mpi" io
ls *.openss | grep "sweep3d.mpi-io\." > sweep3d_intel_create_io

echo ""
echo "-------------------------------------"
echo "BEGIN Analyzing sweep3d.mpi io experiment"
echo "-------------------------------------"
sed 's/^/exprestore -f /' sweep3d_intel_create_io > new_input.script
echo "log -f sweep3d_intel_io_results.log" >> new_input.script
cat common_commands >> new_input.script
openss -batch < new_input.script

grep "630  __libc_read" sweep3d_intel_io_results.log | cat > sweep3d_intel_io_results.status

echo "-------------------------------------"
echo "END Analyzing sweep3d.mpi io experiment"
echo "-------------------------------------"
echo ""


openss -offline -f "/usr/bin/srun -N \$NodeCount -n \$RankCount -p pdebug ./sweep3d.mpi" iot
ls *.openss | grep "sweep3d.mpi-iot\." > sweep3d_intel_create_iot

echo ""
echo "-------------------------------------"
echo "BEGIN Analyzing sweep3d.mpi iot experiment"
echo "-------------------------------------"
sed 's/^/exprestore -f /' sweep3d_intel_create_iot > new_input.script
echo "log -f sweep3d_intel_iot_results.log" >> new_input.script
cat common_commands >> new_input.script
openss -batch < new_input.script

grep "630  __libc_read" sweep3d_intel_iot_results.log | cat > sweep3d_intel_iot_results.status

echo "-------------------------------------"
echo "END Analyzing sweep3d.mpi iot experiment"
echo "-------------------------------------"
echo ""


openss -offline -f "/usr/bin/srun -N \$NodeCount -n \$RankCount -p pdebug ./sweep3d.mpi" mpi
ls *.openss | grep "sweep3d.mpi-mpi\-" > sweep3d_intel_create_mpi

echo ""
echo "-------------------------------------"
echo "BEGIN Analyzing sweep3d.mpi mpi experiment"
echo "-------------------------------------"
sed 's/^/exprestore -f /' sweep3d_intel_create_mpi > new_input.script
echo "log -f sweep3d_intel_mpi_results.log" >> new_input.script
cat common_commands >> new_input.script
openss -batch < new_input.script

grep "\$RankCount  PMPI_Finalize" sweep3d_intel_mpi_results.log | cat > sweep3d_intel_mpi_results.status

echo "-------------------------------------"
echo "END Analyzing sweep3d.mpi mpi experiment"
echo "-------------------------------------"
echo ""


openss -offline -f "/usr/bin/srun -N \$NodeCount -n \$RankCount -p pdebug ./sweep3d.mpi" mpit

#
# Find corresponding experiment database files and create files that can be used to restore the databases
#
ls *.openss | grep "sweep3d.mpi-mpit\-" > sweep3d_intel_create_mpit

#
# Use the corresponding experiment database file names to restore the database and print out the status and results for the experiments
#
echo ""
echo "-------------------------------------"
echo "BEGIN Analyzing sweep3d.mpi mpit experiment"
echo "-------------------------------------"
sed 's/^/exprestore -f /' sweep3d_intel_create_mpit > new_input.script
echo "log -f sweep3d_intel_mpit_results.log" >> new_input.script
cat common_commands >> new_input.script
openss -batch < new_input.script

grep "\$RankCount  PMPI_Finalize" sweep3d_intel_mpi_results.log | cat > sweep3d_intel_mpi_results.status

echo "-------------------------------------"
echo "END Analyzing sweep3d.mpi mpit experiment"
echo "-------------------------------------"
echo ""


#
# End of nested script
#
exit
EOF

echo "pwd=$pwd"

RUN_DIR=$testpath
echo "RUN_DIR=$RUN_DIR"
cd $RUN_DIR
REQ_WALLTIME=1:00
REQ_NNODES=2
REQ_SCRIPT="$RUN_DIR/sweep3d_intel_script.sh"
#script sweep3d_intel_script_results.txt
sh ${REQ_SCRIPT}
#exit

# sweep_intel_email.sh

cat > sweep_intel_email.sh << EOF
#! /bin/bash


#
# Read in test parameters
#
# script defaults
NodeCount=2
RankCount=16
CompilerType="gnu"
EmailAddress="jegkas@gmail.com"

if [ -a default_test_config ] 
then
  n=0
  while read curline; do
    n=`expr \$n + 1`
    echo "\$curline"
    echo "\$n" 

    if [ \$n == 1 ]
    then
       NodeCount=\$curline
    elif [ \$n == 2 ]
    then
       RankCount=\$curline
    elif [ \$n == 3 ]
    then
       CompilerType=\$curline
    elif [ \$n == 4 ]
    then
       EmailAddress=\$curline
    fi
  done < "default_test_config"
fi

#
if [ debug_flag == 1 ]
then
  echo "NodeCount: \$NodeCount"
  echo "RankCount: \$RankCount"
  echo "CompilerType: \$CompilerType"
  echo "EmailAddress: \$EmailAddress"
fi

# script to send test results email
# email subject
SUBJECT="LLNL OpenSpeedShop MPI sweep3d.mpi executable test results"
# Email To ?
EMAIL=\$EmailAddress
# Email text/message
EMAILMESSAGE="/tmp/openss_test_message.txt"
echo " OpenSpeedShop Performance Tool SWEEP3D.MPI Test Results" >\$EMAILMESSAGE
echo "" >>\$EMAILMESSAGE
echo " Intel compiler, \$NodeCount Nodes \$RankCount ranks">> \$EMAILMESSAGE
thisuname=`uname -srnmo`
echo " System uname: " \$thisuname>> \$EMAILMESSAGE
thisdate=`date`
echo " Date/time of run: " \$thisdate>> \$EMAILMESSAGE
thisdir=`pwd`
echo " Directory where tests were run: " \$thisdir>> \$EMAILMESSAGE
echo "" >>\$EMAILMESSAGE
#
testval=`ls *.status | wc -l`
echo " Expected tests: 8">> \$EMAILMESSAGE
echo " Completed tests: " \$testval>> \$EMAILMESSAGE
#
# if the status file exists and has data then the test succeeded
# if the status file does not exist then the test did not complete and consider it failed
#
if [ -a sweep3d_intel_pcsamp_results.status ]
then
  if [ -s sweep3d_intel_pcsamp_results.status ]
  then
    echo " PCSAMP EXPERIMENT PASSED">> \$EMAILMESSAGE
  else
    echo " PCSAMP EXPERIMENT FAILED">> \$EMAILMESSAGE
  fi
else
  echo " PCSAMP EXPERIMENT FAILED">> \$EMAILMESSAGE
fi

#
# if the status file exists and has data then the test succeeded
# if the status file does not exist then the test did not complete and consider it failed
#
if [ -a sweep3d_intel_usertime_results.status ]
then
  if [ -s sweep3d_intel_usertime_results.status ]
  then
    echo " USERTIME EXPERIMENT PASSED">> \$EMAILMESSAGE
  else
    echo " USERTIME EXPERIMENT FAILED">> \$EMAILMESSAGE
  fi
else
  echo " USERTIME EXPERIMENT FAILED">> \$EMAILMESSAGE
fi

#
# if the status file exists and has data then the test succeeded
# if the status file does not exist then the test did not complete and consider it failed
#
if [ -a sweep3d_intel_hwc_results.status ]
then
  if [ -s sweep3d_intel_usertime_results.status ]
  then
    echo " HWC EXPERIMENT PASSED">> \$EMAILMESSAGE
  else
    echo " HWC EXPERIMENT FAILED">> \$EMAILMESSAGE
  fi
else
  echo " HWC EXPERIMENT FAILED">> \$EMAILMESSAGE
fi

#
# if the status file exists and has data then the test succeeded
# if the status file does not exist then the test did not complete and consider it failed
#
if [ -a sweep3d_intel_hwctime_results.status ]
then
  if [ -s sweep3d_intel_hwctime_results.status ]
  then
    echo " HWCTIME EXPERIMENT PASSED">> \$EMAILMESSAGE
  else
    echo " HWCTIME EXPERIMENT FAILED">> \$EMAILMESSAGE
  fi
else
  echo " HWCTIME EXPERIMENT FAILED">> \$EMAILMESSAGE
fi

#
# if the status file exists and has data then the test succeeded
# if the status file does not exist then the test did not complete and consider it failed
#
if [ -a sweep3d_intel_io_results.status ]
then
  if [ -s sweep3d_intel_io_results.status ]
  then
    echo " I/O EXPERIMENT PASSED">> \$EMAILMESSAGE
  else
    echo " I/O EXPERIMENT FAILED">> \$EMAILMESSAGE
  fi
else
  echo " I/O EXPERIMENT FAILED">> \$EMAILMESSAGE
fi

#
# if the status file exists and has data then the test succeeded
# if the status file does not exist then the test did not complete and consider it failed
#
if [ -a sweep3d_intel_iot_results.status ]
then
  if [ -s sweep3d_intel_iot_results.status ]
  then
    echo " I/O TRACE EXPERIMENT PASSED">> \$EMAILMESSAGE
  else
    echo " I/O TRACE EXPERIMENT FAILED">> \$EMAILMESSAGE
  fi
else
  echo " I/O TRACE EXPERIMENT FAILED">> \$EMAILMESSAGE
fi

#
# if the status file exists and has data then the test succeeded
# if the status file does not exist then the test did not complete and consider it failed
#
if [ -a sweep3d_intel_mpi_results.status ]
then
  if [ -s sweep3d_intel_mpi_results.status ]
  then
    echo " MPI EXPERIMENT PASSED">> \$EMAILMESSAGE
  else
    echo " MPI EXPERIMENT FAILED">> \$EMAILMESSAGE
  fi
else
  echo " MPI EXPERIMENT FAILED">> \$EMAILMESSAGE
fi

#
# if the status file exists and has data then the test succeeded
# if the status file does not exist then the test did not complete and consider it failed
#
if [ -a sweep3d_intel_mpit_results.status ]
then
  if [ -s sweep3d_intel_mpit_results.status ]
  then
    echo " MPI TRACE EXPERIMENT PASSED">> \$EMAILMESSAGE
  else
    echo " MPI TRACE EXPERIMENT FAILED">> \$EMAILMESSAGE
  fi
else
  echo " MPI TRACE EXPERIMENT FAILED">> \$EMAILMESSAGE
fi
#echo "This is an email message test">> \$EMAILMESSAGE
#echo "This is email text" >>\$EMAILMESSAGE
# send an email using /bin/mail
/bin/mail -s "\$SUBJECT" "\$EMAIL" < \$EMAILMESSAGE
EOF

# Send out the results for sweep3d.mpi
# sweep_intel_email.sh
EMAIL_REQ_SCRIPT="$RUN_DIR/sweep_intel_email.sh"
sh ${EMAIL_REQ_SCRIPT}

fi

# end loop through the compiler list
done

# end loop through the test list
done

exit
cd $testpathbase


