#!/usr/local/bin/python

from sys import *
import sys 
import os
from time import *

resultsfile = 'tempfile' #the file which the results of the tests are written to
expectedfile = 'expected_output' #the expected output for the tests

listname = 'test_list'
executable_name = ''
v_input = ''
v_output = ''
testResultsFile = ''

def RunWithExecutable(testname, executable_name):
	#if v_input == 'NONE':
	os.system('./'+testname +'>>'+resultsfile)
	#else:
	#	os.system('./'+testname + ' '+executable_name +' ' + v_input + ' >> ' + resultsfile)
	

def RunWithoutExecutable(testname):
	#os.system('./'+testname+ ' >> '+resultsfile)
	print testname + ' result is: '
	os.system('./'+testname)


def OutputCompare(testname, exp_input, typeofrun):
        #if typeofrun == 1:
         #       RunWithoutExecutable(testname)

        #if typeofrun == 2:
         #       RunWithExecutable(testname, executable_name)

        checkcore = os.system('test -e core')

        if checkcore == 0:

                print 'core dump'

	currTime = strftime("%d_%m_%Y_%H%M%S", localtime())
	
	testResultsFile = 'testresults_' + currTime 

	results_input = open(resultsfile, 'r')

	report_input = open(testResultsFile, 'w')

	resultsfilenameinput = open('testresultsfilename', 'w')
	resultsfilenameinput.write(testResultsFile)
	resultsfilenameinput.close()
	while 1:
		results_line = results_input.readline()
		expected_line = exp_input.readline()
		if not results_line:
			break
		if not expected_line:
			break
		else: 
			results_value = results_line[0:-1]	
			expected_value = expected_line[0:-1]
			if results_value == expected_value:
				print 'in ljksdfh;'
				print testname
				report_input.write(testname + ' PASSED \n')

			else:
				report_input.write(testname + ' FAILED \n')
				report_input.write('result was: ' + results_value + '\n')
				report_input.write('result should have been: ' + expected_value + '\n')


def CreateOutput(runtype): 

	#os.system('rm ' + resultsfile)
	#os.system('rm testresults')
	#os.system('make')

	test_input = open(listname, 'r')
	expected_input = open(expectedfile, 'r')

	while 1:
		tests_line = test_input.readline()
		if not tests_line:
			break
		else:
			name_of_test = tests_line[0:-1]
			OutputCompare(name_of_test, expected_input, runtype)
			RunWithoutExecutable(name_of_test)
			os.system('rm test_db');
		

	

def CreateTestList(whichLanguage):

	checktemptestlist = os.system('test -e temptestlist')
	if checktemptestlist == 0:
		os.system('rm -f temptestlist')
	
		
	os.system('ls -1 *.'+ whichLanguage +'>> temptestlist')
	input_tests = open('temptestlist', 'r')
	output_expected = open(expectedfile, 'w')
	output_testlist = open(listname, 'w')
	
	while 1:
		testlist_line = input_tests.readline()
		if not testlist_line:
			break
		else:
			i = 0
			temp_char = ' '
			while temp_char != '.':
				temp_char = testlist_line[i]
				i = i+1
			test_name = testlist_line[0:i-1]
		output_testlist.write(test_name + '\n')
		output_expected.write('PASS' + '\n')


def ReadConfigFile(executable_name, v_input, v_output):
	con_input = open('test_config', 'r')
	counter = 0
	while 1:
	  	config_line = con_input.readline()
		if not config_line:
			break
		if counter == 2:
			executable_name = config_line
		elif counter == 3:
			v_input = config_line
		elif counter == 4:
			v_output = config_line
			
		counter = counter + 1
	con_input.close()

if __name__ == '__main__':
	os.system('touch tempfile')

	checkForTestResultsFile = os.path.isfile('testresultsfilename')
	
	if checkForTestResultsFile:
		os.system('rm testresultsfilename')

	isSimple = 0

	if len(argv) == 2:
		simple_language = argv[1]
		
		checkfiles_test = os.system('test -e ' + listname)
		if checkfiles_test == 0:
			os.system('rm ' + listname)
			
		checkfiles_expected = os.system('test -e ' + expectedfile)
		if checkfiles_expected == 0:
			os.system('rm ' + expectedfile)
		if (simple_language == '-cxx'):
			CreateTestList('cxx')
			isSimple = 1

		if (simple_language == '-c'):
			CreateTestList('c')
			isSimple = 1

		if (simple_language == '-f'):
			CreateTestList('f90')
			isSimple = 1

		runtype = 1

	     	if (simple_language == '-help'):
			runtype = 3


	else:
		runtype = 1

	if (runtype == 3):
		print "Rununit has the following options:"
		print "-cxx, which indicates the files checked in are C++ files"
		print "-c, which indicates the files checked in are C files"
		print "-f, which indicates the files checked in are Fortran files"
		print "These options should be chosen if the developer only checked in unit tests"
		print "If the developer checked in the test list and expected output, don't use the options."
	else:
	       	ReadConfigFile(executable_name, v_input, v_output)
		
		if (executable_name != 'NONE'):
			runtype = 2
			
	
       	CreateOutput(runtype)
	#os.system('make clobber')
		
	if isSimple:
		os.remove('test_list')
       	os.remove('tempfile')

        checktemptestlist = os.system('test -e temptestlist')
        if checktemptestlist == 0:
                os.system('rm -f temptestlist')

		 
			
			

