######################################################################
# Automatically generated by qmake (1.07a) Wed Apr 28 13:37:28 2004
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += dirview.h
SOURCES += dirview.cpp main.cpp
