#!/bin/sh

export SYSTYPE=`uname -s`
echo SYSTYPE=$SYSTYPE
export SYSNAME=`uname -n`
echo SYSNAME=$SYSNAME

if [[ $1 = --help ]]
then
  echo "ft [-cli] [executable] [experiment] [pid] [host] [--help]"
  echo "  where:"
  echo "    -cli:         brings up the future in command line mode"
  echo "    executable:   loads the executable file"
  echo "    experiment:   loads the exeriment file"
  echo "    pid:          attaches (or plans to attach) to process id"
  echo "    host:         targets processes on host machine, host"
  echo "    --help:       This help text."
  exit
fi

export FUTURE_TOOL_RELOCATABLE_NAME=ftgui.so
export FUTURE_TOOL_ENTRY_POINT=gui_init
set +x
if [ $SYSTYPE = "Linux" ] ; then
  if [ $SYSNAME = "hope.americas.sgi.com" ] ; then
    export FUTURE_TOOL_PLUGIN_DIR=$WORKAREA/GUI/plugin/lib/futuretool
    export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$FUTURE_TOOL_PLUGIN_DIR
    if [[ $1 = -cli ]]
    then
      $WORKAREA/GUI/cli/cli $@
    else
#      $WORKAREA/GUI/ftd -ns -fn -misc-fixed-bold-r-normal--13-100-100-100-c-70-iso8859-1 $@
      $WORKAREA/GUI/ftd -ns -fn 6x13 $@
    fi
  else 
#   home linux
    export FUTURE_TOOL_PLUGIN_DIR=$WORKAREA/GUI/plugin/lib/futuretool
    echo FUTURE_TOOL_PLUGIN_DIR=$FUTURE_TOOL_PLUGIN_DIR
    export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$FUTURE_TOOL_PLUGIN_DIR
    export LD_LIBRARYN32_PATH=$LD_LIBRARYN32_PATH:$LD_LIBRARY_PATH
    if [[ $1 = -cli ]]
    then
      $WORKAREA/GUI/cli/cli $@
    else
      $WORKAREA/GUI/ftd -ns -fn 6x13 $@
    fi
  fi
else
# sgi irix
  export FUTURE_TOOL_PLUGIN_DIR=/a45/stipek/QtPC/plugin/lib/futuretool
  echo FUTURE_TOOL_PLUGIN_DIR=$FUTURE_TOOL_PLUGIN_DIR
  export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$FUTURE_TOOL_PLUGIN_DIR
  if [[ $1 = -cli ]]
  then
    /home/tulip22/stipek/QtPC/cli/cli $@
  else
    ftd $@
  fi
fi
