#!/bin/sh

export SYSTYPE=`uname -s`
echo SYSTYPE=$SYSTYPE
export SYSNAME=`uname -n`
echo SYSNAME=$SYSNAME

if [[ $1 = --help ]]
then
  echo "ft [-cli] [executable] [experiment] [pid] [host] [--help]"
  echo "  where:"
  echo "    -cli:         brings up the future in command line mode"
  echo "    executable:   loads the executable file"
  echo "    experiment:   loads the exeriment file"
  echo "    pid:          attaches (or plans to attach) to process id"
  echo "    host:         targets processes on host machine, host"
  echo "    --help:       This help text."
  exit
fi

if [ "$FUTURE_TOOL_PLUGIN_DIR" = "" ]
then
  echo "FUTURE_TOOL_PLUGIN_DIR not set."
  echo "For oss developers that's usually .../GUI/plugin/lib/futuretool"
  exit
fi

export FUTURE_TOOL_RELOCATABLE_NAME=ftgui.so
export FUTURE_TOOL_ENTRY_POINT=gui_init
set +x
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$FUTURE_TOOL_PLUGIN_DIR
export LD_LIBRARYN32_PATH=$LD_LIBRARYN32_PATH:$LD_LIBRARY_PATH
if [[ $1 = -cli ]]
then
  $FUTURE_TOOL_PLUGIN_DIR/../../bin/cli $@
else
FONTNAME="-adobe-helvetica-medium-r-normal--14-120-75-75-p-70-iso8859-1"
  $FUTURE_TOOL_PLUGIN_DIR/../../bin/ftd -fn $FONTNAME $@
fi
