#!/bin/sh
export SYSTYPE=`uname -s`
echo SYSTYPE=$SYSTYPE
export SYSNAME=`uname -n`
echo SYSNAME=$SYSNAME

set +x
if [ $SYSTYPE = "Linux" ] ; then
  if [ $SYSNAME = "hope.americas.sgi.com" ] ; then
    export FUTURE_TOOL_PLUGIN_DIR=/home/tulip22/stipek/OpenSpeedShop/GUI/plugin/lib/futuretool
    clear;cd /home/tulip22/stipek/OpenSpeedShop/GUI;MC;bootstrap;configure --prefix=$FUTURE_TOOL_PLUGIN_DIR/../..;make;make install;
  else
#   home linux
    export FUTURE_TOOL_PLUGIN_DIR=/home/stipek/QtPC/plugin/lib/futuretool
    clear;cd QtPC;MC;bootstrap;configure --prefix=$FUTURE_TOOL_PLUGIN_DIR/../..;make;make install;
  fi
else
# sgi irix
  MC;
fi

