////////////////////////////////////////////////////////////////////////////////
// Copyright (c) 2007 William Hachfeld. All Rights Reserved.
//
// This program is free software; you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free Software
// Foundation; either version 2 of the License, or (at your option) any later
// version.
//
// This program is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
// FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
// details.
//
// You should have received a copy of the GNU General Public License along with
// this program; if not, write to the Free Software Foundation, Inc., 59 Temple
// Place, Suite 330, Boston, MA  02111-1307  USA
////////////////////////////////////////////////////////////////////////////////

/** @file
 *
 * Declaration of the DyninstCallbacks namespace.
 *
 */

#ifndef _OpenSpeedShop_Framework_DyninstCallbacks_
#define _OpenSpeedShop_Framework_DyninstCallbacks_

#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <BPatch.h>



namespace OpenSpeedShop { namespace Framework {

    class ThreadNameGroup;

    /**
     * Dyninst callbacks.
     *
     * Namespace containing the Dyninst callback functions. These callbacks
     * are registered with Dyninst by the daemon's main() and will handle all
     * asynchronous events generated by Dyninst.
     *
     * @ingroup Implementation
     */
    namespace DyninstCallbacks
    {
	void dynLibrary(BPatch_thread*, BPatch_module*, bool);
	void error(BPatchErrorLevel, int, const char* const*);
	void exec(BPatch_thread*);
	void exit(BPatch_thread*, BPatch_exitType);	
	void postFork(BPatch_thread*, BPatch_thread*);
	void threadCreate(BPatch_process*, BPatch_thread*);
	void threadDestroy(BPatch_process*, BPatch_thread*);

	void sendSymbolsForThread(const ThreadNameGroup&);
    }
    
} }



#endif
