.\" Process this file with
.\" groff -man -Tascii OpenSpeedShop_online.3
.\"
.TH OpenSpeedShop_online 3 "June, 2009" "Open|SpeedShop Reference" "Open|SpeedShop"

.SH NAME
OpenSpeedShop \- Application Performance Tool Online Mode of Operation

.SH SYNOPSIS

.BR Overview

The Open|SpeedShop performance tool gathers information about the user 
application performance such as inclusive and exclusive CPU time, hardware 
counter events and time, detailed information about I/O events/calls, 
detailed information about MPI events/calls, and floating point exceptions 
that occurred in the user application.  The term experiment is used to 
describe the application and the type of performance data being gathered.   

One of the ways Open|SpeedShop uses to gather the performance data, online,
is the topic of this man page.  The mode of instrumentation in 
Open|SpeedShop refers to the manner in which the user application is 
instrumented to allow the application execution to produce performance 
information, in addition to the applications normal output.  In the online 
mode, the Open|SpeedShop performance data collectors are interjected into the 
user application through dynamic instrumentation, via the Dyninst component
in Open|SpeedShop.  When the online mode of operation is used (-online option 
to openss, currently the default), then the application can either be started 
from the beginning or can be attached to while already running.  The advantage
to the online mode of operation is the flexibility to attach to processes 
that are already running, view the data on demand (while application is still
running), and then detach from the application.


.SH SEE ALSO

The OpenSpeedShop Web site: www.openspeedshop.org

.BR openss (1),
.BR osspcsamp (1),
.BR ossusertime (1),
.BR osshwc (1),
.BR osshwctime (1),
.BR ossio (1),
.BR ossiot (1),
.BR ossmpi (1),
.BR ossmpit (1),
.BR ossmpiotf (1),
.BR ossfpe (1)
.BR OpenSpeedShop (3)
.BR OpenSpeedShop_offline (3)


