////////////////////////////////////////////////////////////////////////////////
// Copyright (c) 2004 Silicon Graphics, Inc. All Rights Reserved.
//
// This library is free software; you can redistribute it and/or modify it under
// the terms of the GNU Lesser General Public License as published by the Free
// Software Foundation; either version 2.1 of the License, or (at your option)
// any later version.
//
// This library is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
// FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more
// details.
//
// You should have received a copy of the GNU Lesser General Public License
// along with this library; if not, write to the Free Software Foundation, Inc.,
// 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
////////////////////////////////////////////////////////////////////////////////

/** @file
 *
 * Declaration and definition of the TypedMetric template.
 *
 */

#ifndef _OpenSpeedShop_Framework_TypedMetric_
#define _OpenSpeedShop_Framework_TypedMetric_

#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include "Metric.hxx"

#include <string>
#include <typeinfo>



namespace OpenSpeedShop { namespace Framework {

    /**
     * Typed metric with metadata.
     *
     * Template for a typed metric with metadata. The metric value's type is
     * specified by the template instantiation while its metadata is specified
     * at object construction. Used for specifying data generated by performance
     * data collectors such that runtime introspection of that data is possible.
     *
     * @ingroup CollectorAPI
     */
    template <typename T>
    class TypedMetric :
	public Metric
    {

    public:

	/** Constructor from metadata. */
	TypedMetric(const std::string& unique_id,
		    const std::string& short_name,
		    const std::string& description) :
	    Metric(unique_id, short_name, description, typeid(T))
	{	    
	}
	
    };
    
} }



#endif
