  plugin_entry->grouping = "TOPLEVEL";
  plugin_entry->show_immediate = 0;
  plugin_entry->plugin_description = "PLUGIN_DESCRIPTION";
  plugin_entry->plugin_name =  "pcSamplePanel.so";
  plugin_entry->plugin_location = "$FUTURE_TOOL_PLUGIN_DIR";
  plugin_entry->plugin_entry_point = "panel_init";
  plugin_entry->menu_heading =  "Performance";
  plugin_entry->menu_label =  "pc Sampling";
  plugin_entry->panel_type =  "pc Sampling";
