  plugin_entry->grouping = "";
  plugin_entry->show_immediate = 0;
  plugin_entry->plugin_description = "PLUGIN_DESCRIPTION";
  plugin_entry->plugin_name =  "UserTimePanelWizard.so";
  plugin_entry->plugin_location = "$FUTURE_TOOL_PLUGIN_DIR";
  plugin_entry->plugin_entry_point = "panel_init";
  plugin_entry->menu_heading =  "Wizards";
  plugin_entry->menu_label =  "User Time Wizard";
  plugin_entry->panel_type =  "User Time Wizard";
