######################################################################
# Automatically generated by qmake (1.04a) Tue Nov 11 12:21:03 2003
######################################################################

TEMPLATE = app
CONFIG -= moc
INCLUDEPATH += .

# Input
SOURCES += gui.cpp
