.\" Process this file with
.\" groff -man -Tascii ossmpiotf.1
.\"
.TH OSSMPIOTF 1 "JUNE 2009" Linux "User Manuals"
.SH NAME
ossmpiotf \- DEPRECATED IN CBTF VERSION Open|SpeedShop MPI Tracing Open Trace Format (OTF) experiment script
.SH SYNOPSIS
.nf
.IP "ossmpiotf simple_executable [ MPIOTF_FUNCTION_LIST ]"
.IP "ossmpiotf ""executable args"" [ MPIOTF_FUNCTION_LIST ] "
.IP "ossmpiotf ""multi_executable"" [ MPIOTF_FUNCTION_LIST ] "
.fi

.SH TYPICAL USAGE FORM
.nf

ossmpiotf "multi_executable"

For example:

ossmpiotf "/opt/openmpi/bin/mpirun -np 4 /u/user/mpi_prog" 

.fi
.SH DESCRIPTION
.B ossmpiotf

ossmpiotf is a convenience command script that invokes the 
Open|SpeedShop application level performance tool to gather 
MPI function trace performance information about
the application being monitored and reports that information 
back to the user in order to locate MPI performance 
bottlenecks in user applications.

ossmpiotf captures several of the MPI system calls 
and records the time spent and the number of calls in each routine.
The call path/stack is also recorded.  This allows the user to 
interrogate the call paths/stacks to find out where each MPI call 
has been made in the application program.  In addition, the "mpiotf"
experiment gathers additional information about each individual
MPI call, such as, number of bytes transferred, the source and/or
destination ranks, as well as other MPI function call specific
information.

Information that is presented after the execution of the "mpiotf"
experiment is the exclusive CPU time spent inside all the system
MPI functions, specified to be traced, in the users application program. 
In addition, to the time spent in the MPI functions, the call paths to
where the MPI function was called in the user application is also presented
to the user.  Individual call paths and their respective times are
also available.  In addition, the "mpiotf" experiment views optionally provide
the capability to view each MPI function call and the attributes related
to that particular MPI function call.  For example, for a "MPI_Send" function call
the optional output would contain the source and destination ranks as well as the
of bytes transferred.  The optional "trace" view option will present the chronologically
ordered list of MPI function calls with the optional call specific information.


.SH OPTIONS

.IP "simple_executable"
This option specifies the simple executable to be run. By 
simple executable we mean a one word command with no arguments.
No quotes around the executable name are needed when the command
is a single word command with no arguments.

.IP " ""executable args"" "
This option specifies an executable with arguments to be run. In
this case the executable can be a one word command or a multiple word
(multiple tokens) command, such as a mpi command specification. 
For example:

        "simple_executable -n 40 40 40"

or

        "/opt/mpi/mpirun -np 64 ./executable_name" 

Open|SpeedShop requires quotes around the executable and arguments when 
the executable command is not simple.

.IP " ""multi_executable [args]"" "
This option specifies a multiple word executable with or without
arguments to be run. In this case the executable is multiple word 
command or a multiple word command, such as a mpi command 
specification. For example: 

        "/opt/mpi/mpirun -np 64 ./executable_name" 

Open|SpeedShop requires quotes around the executable and arguments when 
the executable command is not simple.

.IP "MPIOTF_FUNCTION_LIST"
Specify a list of system MPI functions to be traced.  If the OPENSS_MPIOTF_TRACED
is set, this value will override the function list defined by OPENSS_MPIOTF_TRACED.
the resulting value is used as the MPI function list for the experiment being run.

.nf
MPI Category                    Argument
--------------------------      --------------------
All MPI Functions               all
Collective Communicators        collective_com
Persistent Communicators        persistent_com
Synchronous Point to Point      synchronous_p2p
Asynchronous Point to Point     asynchronous_p2p
Asynchronous Non-blocking       async_nonblocking
Process Topologies              process_topologies
Groups Contexts Communicators   graphs_contexts_comms
Environment                     environment
Datatypes                       datatypes
MPI File I/O                    fileio
.fi


.IP "default"
Force the experiment to use the default MPI function list value when running
the experiment. This overrides the OPENSS_MPIOTF_TRACED environment variable
if it was set.

.IP "<no arguments>"
If no optional arguments are specified then the default MPI function 
list value is used in the experiment run.  However, if the OPENSS_MPIOTF_TRACED
environment variable is set then that MPI function list value will be 
used in the experiment run.


.SH FILES
.IP ~/.qt/openspeedshoprc
.RS
The Open|SpeedShop preference configuration file which is 
accessed through the Open|SpeedShop GUI Preferences menu item.
This file contains several options which allow the user to 
configure Open|SpeedShop to better fit their needs.

See the Open|SpeedShop Users Guide for full details on the
preferences available.
.RE

.SH ENVIRONMENT
.IP OPENSS_RAWDATA_DIR (offline mode of operation only)
On a cluster where /tmp is not shared across nodes, this
environment variable needs to be set to a path to a shared
file system that is accessible from all the nodes of the
cluster.  The offline mode of operation for Open|SpeedShop
needs a shared file system location to write the files containing
the performance information from each process on all the
nodes of the cluster involved in the experiment.  The online
version of Open|SpeedShop can also use this variable to take
advantage of faster file systems, but it is not required in the
same sense as it is when running in offline mode.  If /tmp is not
a shared file system and OPENSS_RAWDATA_DIR is not set, then the
performance data from the nodes where /tmp is not shared will not
be available in the Open|SpeedShop view of the experiment data.

.IP OPENSS_MPIOTF_TRACED
This environment variable specifies the MPI function list that
the ossmpiotf will trace during the experiment run.

.SH DIAGNOSTICS
The following diagnostics may be TBD:

.SH QUICK START EXAMPLE
The following command runs the MPI executable "mpi_prog" and gathers 
MPI function trace information on the 64 ranked processes.  

.nf

ossmpiotf "/opt/openmpi/bin/mpiexec -np 64 /home/user/mpi_prog"
.fi

.SH BUGS
TBD

.SH AUTHOR
Open|SpeedShop Team <oss-questions@openspeedshop.org>
.SH "SEE ALSO"
.BR openss (1),
.BR osscompare (1)
.BR osspcsamp (1)
.BR ossusertime (1),
.BR osshwc (1)
.BR osshwctime (1)
.BR ossio (1)
.BR ossiot (1)
.BR ossmpi (1)
.BR ossmpip (1)
.BR ossmpiotf (1)
.BR ossfpe (1)


