######################################################################
# Automatically generated by qmake (1.07a) Wed Apr 28 13:38:19 2004
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h qfileiconview.h ../dirview/dirview.h
SOURCES += main.cpp mainwindow.cpp qfileiconview.cpp ../dirview/dirview.cpp
